### ISSUE TITLE
KamelConfig.Default does not load automatically with v1 beta

### ISSUE THREAD

**Issue by DjuroRad** [Kamel-Media/Kamel#97] opened 2024-02-27 12:28 UTC
Steps to reproduce:

Use KMP wizard by following [this](https://kmp.jetbrains.com/) link and create multiplatform project sharing UI for iOS and Android
Use version of kamel `1.0.0-beta.1` (ktor client version `2.3.8`)
```
KamelImage(
            resource = asyncPainterResource(data = "https://picsum.photos/200"),
            contentDescription = null,
            modifier = Modifier
                .size(230.dp)
                .background(color = Color.Green),
            onFailure = {
                Text(text = "failed")
            },
            onLoading = {
                Text(text = "loading")
            }
        )
```

Result: `KamelImage`'s `onFailed` will be rendered

**Comment by luca992** [comment] 2024-02-28 23:02
no that should be fine.

are you using `implementation("media.kamel:kamel-image-default:1.0.0-beta.1")`?

I can't really help you without more details or at least the stack trace of the error that is being passed to `onFailure`

**Comment by DjuroRad** [comment] 2024-02-29 08:26
Yes, I am using `kamel-image-default` name from `media.kamel` group. I tried it with almost any name available.  
I tried with other names from your group also, added `kamel-decoder-image-bitmap` just in case. Also tried adding 
`implementation( "org.jetbrains.kotlin:kotlin-reflect:1.9.21")` explicitly but that didn't help either

Sorry about forgeting the stacktrace, here it is
```
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  java.lang.IllegalStateException: Unable to find a decoder for interface androidx.compose.ui.graphics.ImageBitmap (Kotlin reflection is not available) 
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I   message: Unable to find a decoder for interface androidx.compose.ui.graphics.ImageBitmap (Kotlin reflection is not available)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  stacktrace: java.lang.IllegalStateException: Unable to find a decoder for interface androidx.compose.ui.graphics.ImageBitmap (Kotlin reflection is not available)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at io.kamel.core.ImageLoadingKt$loadImageBitmapResource$$inlined$loadResource$1.invokeSuspend(ImageLoading.kt:107)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at io.kamel.core.ImageLoadingKt$loadImageBitmapResource$$inlined$loadResource$1.invoke(Unknown Source:8)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at io.kamel.core.ImageLoadingKt$loadImageBitmapResource$$inlined$loadResource$1.invoke(Unknown Source:4)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.flow.FlowKt__ErrorsKt.catchImpl(Errors.kt:156)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.flow.FlowKt.catchImpl(Unknown Source:1)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at androidx.compose.runtime.SnapshotStateKt__SnapshotFlowKt$collectAsState$1$2.invokeSuspend(SnapshotFlow.kt:66)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2024-02-29 09:22:23.611  9646-9646  System.out              org.example.melodyreservation        I  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by luca992** [comment] 2024-02-29 19:30
reflection shouldn't be required. Did you make you happen to make your own KamelConfig?

If you just need it to work I would suggest using a v0.9 build for now.

**Comment by DjuroRad** [comment] 2024-03-01 09:02
I am using version `0.9.3`. No issues with that version. I didn't make my own `KamelConfig`. It worked out of box in the previous versions. 

Now that you mentioned it, I see that `LocalKamelConfig` defaults to `KamelConfig.Core`
In `KamelConfigImage.kt`
```
public var configOverride: KamelConfig? = null

public val LocalKamelConfig: ProvidableCompositionLocal<KamelConfig> =
    staticCompositionLocalOf { configOverride ?: KamelConfig.Core }
```

And if I update it to `KamelConfig.Default`

```
KamelConfig {
    configOverride = KamelConfig.Default
}
```
it will now work 😃 

I also see that `KamelConfig.Default` uses `takeFrom` from `KamelConfig.Core`

```
public val KamelConfig.Companion.Default: KamelConfig
    get() = KamelConfig {
        takeFrom(KamelConfig.Core)
        imageBitmapDecoder()
        imageVectorDecoder()
        svgDecoder()
        platformSpecificConfig()
    }
```

and beside decoders adds the `expect`ed `platformSpecificConfig()`

Is this intended behaviour? I think it should be provided somewhere within the `README.md` since this happens out of box when using KMP wizard which is used by a lot of people experimenting with compose multiplatform. 
Do you intend to keep it like this or maybe change the `configOverride` to default to `KamelConfig.Default` instead of `KamelConfig.Core`?

Wdyt luca?

**Comment by luca992** [comment] 2024-03-02 00:14
`configOverride` is supposed to be set to `KamelConfig.Default` automatically [here](https://github.com/Kamel-Media/Kamel/blob/e37c7630f2fe48174b390d904e1c76cb06cdf6ab/kamel-image-default/src/commonMain/kotlin/io/kamel/image/config/KamelConfigImageDefault.kt#L23).

If it's not actually working I'll look into it. And the 1.0 build is definitely still a beta. I would hope no one is setting that to be used in a wizard rather than the stable build.

**Comment by DjuroRad** [comment] 2024-03-02 16:45
<img width="585" alt="image" src="https://github.com/Kamel-Media/Kamel/assets/65571380/09621ac1-be55-4cad-a454-a253115cf18a">

Regarding the initializer 😃

**Comment by luca992** [comment] 2024-03-02 17:12
That is intended. 

Are you having this issue on ios only? That is the only target I am able to duplicate it on

**Comment by luca992** [comment] 2024-03-02 18:17
[1.0.0-beta.2](https://github.com/Kamel-Media/Kamel/releases/tag/v1.0.0-beta.2) should work on iOS out of the box without setting your own config

**Comment by DjuroRad** [comment] 2024-03-04 09:55
@luca992 version `beta.2` fixes the issue on iOS but the issues is still present on Android. Same stacktrace and everything. Even if I set the `configOverride` manually on Android it doesn't fix it now. 
On version `beta.1` setting `configOverride = KamelConfig.Default` fixes the issue for both `iosMain` and `androidMain` targets whereas `beta.2` doesn't fix it for Android (iOS works out of box)

**Comment by luca992** [comment] 2024-03-04 20:39
Hmm strange. I couldn't cause the same issue on android. Also,`configOverride` should not be exposed in beta 2 anymore. But either way you should be able to specify the default config to be used with the method described in the readme.

**Comment by DjuroRad** [comment] 2024-03-06 08:14
Yap, but doesn't really work atm

**Comment by luca992** [comment] 2024-03-06 09:46
I was able to duplicate it. But specifying the default config does work.

```
val kamelConfig = remember {
    KamelConfig {
        takeFrom(KamelConfig.Default)
    }
}
CompositionLocalProvider(LocalKamelConfig provides kamelConfig) {
    // your composeable
}
```

**Comment by DjuroRad** [comment] 2024-03-06 12:46
I checked it now with just using withing the main composable called `App` and it works now
```
KamelConfig {
        configOverride = KamelConfig.Default
    }
```

I should've invalidated the caches, my bad

**Comment by luca992** [comment] 2024-03-07 01:13
configOverride is supposed to be internal. Just fyi

**Comment by luca992** [comment] 2024-03-12 09:07
@DjuroRad should be fixed in [1.0.0-beta.3](https://github.com/Kamel-Media/Kamel/releases/tag/v1.0.0-beta.3)

**Closed by luca992** 2024-03-12 09:07 UTC

**Comment by PMARZV** [comment] 2024-03-17 19:36
in jvm desktop windows (1.0.0-beta.5) when "running release distributable" with proguard:
```
obfuscate.set(false)
optimize.set(false)
```
```
Exception in thread "main" java.util.ServiceConfigurationError: io.kamel.image.config.KamelConfigService: Provider io.kamel.image.config.DefaultKamelConfigService not found
	at java.base/java.util.ServiceLoader.fail(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$2.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader$3.hasNext(Unknown Source)
	at java.base/java.util.ServiceLoader.findFirst(Unknown Source)
	at io.kamel.image.config.DetectedKamelConfig_desktopJvmKt.<clinit>(DetectedKamelConfig.desktopJvm.kt:7)
	at io.kamel.image.config.LocalKamelConfigKt$LocalKamelConfig$1.invoke(LocalKamelConfig.kt:1012)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:1029)
	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:90)
```
when Gradle runRelease only, its working without errors

**Comment by JacobCube** [comment] 2024-12-16 18:54
The same just occurred to me on JVM target. When a provided this `val kamelConfig = remember {
        KamelConfig {
            takeFrom(KamelConfig.Default)
        }
    }` It started working. Version 1.0.1

**Comment by luca992** [comment] 2024-12-23 23:58
@JacobCube hmm can you provide a sample or fork the existing sample to reproduce it?
